"""add connect_code

Revision ID: 92bda8901d26
Revises: 632cba0ac3d8
Create Date: 2025-09-26 14:33:54.532649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92bda8901d26'
down_revision = '632cba0ac3d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connect_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('guest_session_id', sa.String(length=64), nullable=True),
    sa.Column('code_type', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_rotated_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guest_session_id', 'is_active', name='uq_guest_active_code'),
    sa.UniqueConstraint('user_id', 'is_active', name='uq_user_active_code')
    )
    with op.batch_alter_table('connect_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connect_codes_code_hash'), ['code_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_connect_codes_guest_session_id'), ['guest_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connect_codes_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_connect_codes_user_id'), ['user_id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connect_code_id', sa.Integer(), nullable=True))
        batch_op.alter_column('hardware_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('mac_address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('device_fingerprint',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_clients_connect_code_id'), ['connect_code_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_device_fingerprint'), ['device_fingerprint'], unique=True)
        batch_op.create_index(batch_op.f('ix_clients_hardware_id'), ['hardware_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_mac_address'), ['mac_address'], unique=False)
        batch_op.create_foreign_key(None, 'connect_codes', ['connect_code_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_clients_mac_address'))
        batch_op.drop_index(batch_op.f('ix_clients_hardware_id'))
        batch_op.drop_index(batch_op.f('ix_clients_device_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_clients_connect_code_id'))
        batch_op.alter_column('device_fingerprint',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('mac_address',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('hardware_id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('connect_code_id')

    op.drop_table('devices')
    with op.batch_alter_table('connect_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connect_codes_user_id'))
        batch_op.drop_index(batch_op.f('ix_connect_codes_is_active'))
        batch_op.drop_index(batch_op.f('ix_connect_codes_guest_session_id'))
        batch_op.drop_index(batch_op.f('ix_connect_codes_code_hash'))

    op.drop_table('connect_codes')
    # ### end Alembic commands ###
