"""add security groups and command blacklist

Revision ID: add_security_groups
Revises: 92bda8901d26
Create Date: 2025-01-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'add_security_groups'
down_revision = '92bda8901d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建安全组表
    op.create_table('security_groups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('group_type', sa.String(length=20), nullable=False),
        sa.Column('parent_group_id', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['parent_group_id'], ['security_groups.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    
    # 创建命令黑名单规则表
    op.create_table('command_blacklist_rules',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('security_group_id', sa.Integer(), nullable=False),
        sa.Column('rule_type', sa.String(length=20), nullable=False),
        sa.Column('rule_value', sa.String(length=255), nullable=False),
        sa.Column('os_type', sa.String(length=20), nullable=True),
        sa.Column('action', sa.String(length=20), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['security_group_id'], ['security_groups.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 为命令黑名单规则表创建索引
    with op.batch_alter_table('command_blacklist_rules', schema=None) as batch_op:
        batch_op.create_index('idx_security_group_priority', ['security_group_id', 'priority'], unique=False)
        batch_op.create_index('idx_rule_type_os', ['rule_type', 'os_type'], unique=False)
    
    # 创建客户端安全组关联表
    op.create_table('client_security_groups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=False),
        sa.Column('security_group_id', sa.Integer(), nullable=False),
        sa.Column('assigned_by', sa.Integer(), nullable=False),
        sa.Column('assigned_at', sa.DateTime(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
        sa.ForeignKeyConstraint(['security_group_id'], ['security_groups.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('client_id', 'is_active', name='uq_client_active_security_group')
    )
    
    # 为客户端安全组关联表创建索引
    with op.batch_alter_table('client_security_groups', schema=None) as batch_op:
        batch_op.create_index('idx_client_security_group', ['client_id', 'security_group_id'], unique=False)
    
    # 创建命令执行日志表
    op.create_table('command_execution_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('session_id', sa.String(length=64), nullable=True),
        sa.Column('command', sa.Text(), nullable=False),
        sa.Column('command_type', sa.String(length=50), nullable=True),
        sa.Column('action', sa.String(length=20), nullable=False),
        sa.Column('security_group_id', sa.Integer(), nullable=True),
        sa.Column('rule_id', sa.Integer(), nullable=True),
        sa.Column('rule_matched', sa.String(length=255), nullable=True),
        sa.Column('ip_address', sa.String(length=64), nullable=True),
        sa.Column('user_agent', sa.String(length=500), nullable=True),
        sa.Column('execution_time', sa.DateTime(), nullable=False),
        sa.Column('response_message', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
        sa.ForeignKeyConstraint(['rule_id'], ['command_blacklist_rules.id'], ),
        sa.ForeignKeyConstraint(['security_group_id'], ['security_groups.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 为命令执行日志表创建索引
    with op.batch_alter_table('command_execution_logs', schema=None) as batch_op:
        batch_op.create_index('idx_client_execution_time', ['client_id', 'execution_time'], unique=False)
        batch_op.create_index('idx_user_execution_time', ['user_id', 'execution_time'], unique=False)
        batch_op.create_index('idx_action_execution_time', ['action', 'execution_time'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除命令执行日志表
    op.drop_table('command_execution_logs')
    
    # 删除客户端安全组关联表
    op.drop_table('client_security_groups')
    
    # 删除命令黑名单规则表
    op.drop_table('command_blacklist_rules')
    
    # 删除安全组表
    op.drop_table('security_groups')
    
    # ### end Alembic commands ###